steps:

  - name: gcr.io/kylepericak/pelican:latest
    entrypoint: pelican
    args: ["/workspace/content", "-o", "/workspace/output"]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./output", "gs://kyle.pericak.com"]
